Working on css 2
GroceryFlux/GroceriesApp pull request #42
Opened 2023-09-14 15:08 UTC by samiletuns

2023-09-14 21:10 UTC, raphael-arce requested changes
Two small suggestions, otherwise looks already pretty good 👍

2023-09-14 21:10 UTC, raphael-arce commented on src/utils/timeStampAndSortBy.js
> +    return 'a few days ago';
I think we should simplify this here. Let‘s try to make it without duplicate and nested branches 👍

2023-09-14 21:10 UTC, raphael-arce commented on src/components/ItemsPage/ListTitleInput.jsx
> +          defaultValue={list.title === 'No title' ? '' : list.title}
I think we should switch things around here: imo it would be simpler to leave the title empty when it‘s empty and only add a condition to show `No Title` in the ListPage, rather than to add the title `No Title` programmatically then show it as empty etc.

2023-09-18 14:21 UTC, samiletuns commented on src/components/ItemsPage/ListTitleInput.jsx
> +          defaultValue={list.title === 'No title' ? '' : list.title}
Switched both, now list won't have title by default and 'No title' will only be displayed when list.title === ''

2023-09-18 14:21 UTC, samiletuns commented on src/utils/timeStampAndSortBy.js
> +    return 'a few days ago';
Improved and removed nested branches

2023-09-21 16:37 UTC, raphael-arce approved these changes
Good job! 👍

2023-09-21 16:38 UTC, merged